# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portal.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionfor',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_by_me', to='portal.Department'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to_me', to='portal.Department'),
        ),
    ]
