# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0002_auto_20170324_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='password',
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
