# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170324_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='deadline',
            field=models.DateField(),
        ),
    ]
