# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20170324_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_recommeded',
            field=models.BooleanField(default=False),
        ),
    ]
