# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20170329_0403'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together=set([]),
        ),
    ]
