# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20170329_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_admisable',
            field=models.BooleanField(default=False),
        ),
    ]
