# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20170401_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_admissed',
            field=models.BooleanField(default=True),
        ),
    ]
